### ISSUE TITLE
Broken relay?

### ISSUE THREAD

**Issue by Dan-Rdd** [burja8x/relay#1]
First I love this concept great work although i have tried to replicate this and when I click start on the relay  and before i even put a card on the mole pm3 I get the following error
110.288 : PROXY       TRACE    File created. 
110.290 : PM C PROXY  INFO     PIPE OK 
110.292 : PM PROXY    INFO     ..Relay.. 
110.342 : PM C PROXY  INFO     received from proxy: OK  len: 1   time: 102 ms 
110.359 : MOLE        TRACE    ping 
110.362 : PM C MOLE   INFO     got ping 
110.366 : MOLE        TRACE    sending back ping data 
110.374 : PM C PROXY  INFO     Received back from Mole OK  len: 1   time: 140 ms 
110.378 : PM C MOLE   INFO     pong send  resp in: 4 ms 
110.388 : PM C PROXY  INFO     received from proxy: OK  len: 9   time: 11 ms 
110.405 : MOLE        TRACE    ping 
110.412 : PM C MOLE   INFO     got ping 
110.414 : MOLE        TRACE    sending back ping data 
110.420 : PM C MOLE   INFO     pong send  resp in: 4 ms 
110.425 : PM C PROXY  INFO     Received back from Mole OK  len: 9   time: 48 ms 
110.443 : PM C PROXY  INFO     received from proxy: OK  len: 17   time: 13 ms 
110.462 : MOLE        TRACE    ping 
110.465 : PM C MOLE   INFO     got ping 
110.467 : MOLE        TRACE    sending back ping data 
110.471 : PM C MOLE   INFO     pong send  resp in: 4 ms 
110.476 : PM C PROXY  INFO     Received back from Mole OK  len: 17   time: 49 ms 
110.679 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
110.881 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
111.083 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
111.285 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
111.487 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
111.689 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
111.891 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
112.093 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
112.294 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
112.496 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
112.698 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
112.900 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
113.101 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
113.303 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
113.505 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
113.707 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
113.909 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
114.112 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
114.312 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
114.513 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
114.716 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
114.918 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
115.120 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
115.322 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
115.524 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
115.726 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
115.928 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
116.130 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
116.332 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
116.536 : PM C PROXY  WARNING  (PING state) Unexpected msg or no msg from proxmark (proxy) status:1   cmd:2161 
116.537 : PM C PROXY  FATAL    Ping proxmark response [31mtimeout[0m 
116.538 : PM C PROXY  INFO     --END RELAY-- 
116.835 : PROXY       TRACE    [PIPE] --END RELAY-- 
117.657 : MOLE        INFO     kill pm3 
117.668 : MOLE        WARNING  KILLING PM3 client if exist. 
117.669 : PM C MOLE   INFO     killing PM3 
117.671 : PM C MOLE   INFO     --END MOLE-- 
117.673 : MOLE        INFO     mole stoped. 

I can sniff between a reader and card and see the data as expected but the relay fails

also I had to manually create the fifo's as the relay app failed to create them these pm3's are both running on pi zero w

be greatful for some feedback / help

**Comment by burja8x** [comment]
_`"PM C PROXY WARNING (PING state) Unexpected msg or no msg from proxmark (proxy) status:1 cmd:2161"`_
This error tells you that the Proxmark on the proxy side didn't respond to the ping. At the beginning, there is a ping process (around 62 pings... 3 pings were successful in your case). This is done to check if communication between the Proxmark (proxy) and Proxmark (mole) works properly. Maybe the USB or Wi-Fi connection is not stable.

**Comment by Dan-Rdd** [comment]
> _`"PM C PROXY WARNING (PING state) Unexpected msg or no msg from proxmark (proxy) status:1 cmd:2161"`_ This error tells you that the Proxmark on the proxy side didn't respond to the ping. At the beginning, there is a ping process (around 62 pings... 3 pings were successful in your case). This is done to check if communication between the Proxmark (proxy) and Proxmark (mole) works properly. Maybe the USB or Wi-Fi connection is not stable.

hmm interesting, the pi's are connected to a decent wifi ap and only they are connected which is only 5m away and the usb cables are new.  hmmm will have to do more debugging :). Thanks for your response

**Comment by Dan-Rdd** [comment]
Got it working and it pretty sweet and also made it with an ad-hoc wifi network to increase the speed, I was hoping to get Mifare Classic working but it seg faults. so I will need to look into that but Ultra lights work with out a issue.
